VIH-6907 - audio recording alert
hmcts/vh-video-web pull request #1042
Opened 2020-12-04 16:29 UTC by levibutler

VIH-6907

### Change description ###
Alert when a problem is detected with the audio recording

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2020-12-04 16:37 UTC, RuwanikaWeerakkody submitted a review, later dismissed

2020-12-04 16:49 UTC, levibutler commented
@shaed-parkar 
oh that’s not right
it should display only when the hearing has started
and should be at the top of the page

ill update acs and try again

2020-12-04 16:51 UTC, shaed-parkar requested changes
The alert should only be visible when the hearing is in session. The alert should also be placed at the top of the screen.

2020-12-07 17:37 UTC, shaed-parkar approved these changes
LGTM

2020-12-08 09:46 UTC, merged