VIH-6931 More logging
hmcts/vh-video-web pull request #1082
Opened 2020-12-20 00:24 UTC by virensareen

### JIRA link (if applicable) ###
VIH-6931

### Change description ###
Added more logging to the controllers

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2020-12-20 10:09 UTC, npoxon submitted a review, later dismissed

2020-12-21 10:15 UTC, levibutler commented on VideoWeb/VideoWeb/Controllers/AudioRecordingController.cs
> +                _logger.LogTrace($"Audio recording successfully stopped for hearingId: {hearingId}");
shouldnt use string interpolation for logging, it wont add as custom property :)

2020-12-21 10:17 UTC, levibutler requested changes
string interpolation changes, also if another active pr gets in first a lot of the logging and test setup would be redundant :)

2020-12-21 16:49 UTC, levibutler commented on VideoWeb/VideoWeb/Controllers/HealthCheckController.cs
> +            _logger.LogTrace("Healthcheck successful.");
not needed

2020-12-21 16:50 UTC, levibutler commented on VideoWeb/VideoWeb/Controllers/UserDataController.cs
> +                _logger.LogTrace($"Court room accounts retrieved successfully");
not needed

2020-12-21 16:50 UTC, levibutler commented on VideoWeb/VideoWeb/Controllers/VenuesController.cs
> +                _logger.LogTrace($"Judge names retrieved successfully");
not needed

2020-12-21 17:13 UTC, levibutler approved these changes

2020-12-21 17:33 UTC, merged