VIH-8604 Fixed Lock/Unlock room status misalignment
hmcts/vh-video-web pull request #1753
Opened 2022-01-06 18:24 UTC by AWildBugAppeared

2022-01-07 09:16 UTC, omio-ma submitted a review, later dismissed

2022-01-07 16:12 UTC, FarronF commented on VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/participant-waiting-room/participant-waiting-room.component.scss
> +  @media screen and (min-width: $breakpoint-small) {
```suggestion
  @include responds-to(small) {
```

2022-01-07 17:15 UTC, FarronF requested changes
Can you post screenshots of how this looks at different sizes? 

I'm not sure this will entirely fix the issue in the ticket. We should probably add something like

white-space: nowrap

to prevent it from wrapping at all.

2022-01-10 12:11 UTC, FarronF approved these changes

2022-01-10 17:20 UTC, omio-ma approved these changes

2022-01-10 17:25 UTC, merged