Convert 'expected states' collection to an array so that the contents…
hmcts/vh-video-web pull request #1782
Opened 2022-01-31 17:04 UTC by ibthmcts

… can be printed when logging

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###
VIH-7638

### Change description ###
Convert 'expected states' collection to an array so that the contents can be printed when logging

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-01-31 17:04 UTC, MichaelKeaneathmcts approved these changes

2022-02-11 16:58 UTC, MichaelKeaneathmcts requested changes

2022-02-11 16:58 UTC, MichaelKeaneathmcts commented on VideoWeb/VideoWeb.AcceptanceTests/Steps/CommonSteps.cs
> +                _browsers[_c.CurrentUser].Driver.WaitUntilVisible(CommonLocators.ElementContainingText("Please wait to be connected")).Displayed.Should().BeTrue();
Is there no identifier for the web element?

2022-02-11 16:58 UTC, MichaelKeaneathmcts commented on VideoWeb/VideoWeb.AcceptanceTests/Steps/CommonSteps.cs
>              _browsers[_c.CurrentUser].Driver.WaitUntilVisible(CommonLocators.ButtonWithInnerText(label)).Displayed.Should().BeTrue();
Is there no identifier for the web element?

2022-02-11 16:58 UTC, MichaelKeaneathmcts commented on VideoWeb/VideoWeb.AcceptanceTests/Steps/JudgePrivateConsultationSteps.cs
> +            _browsers[_c.CurrentUser].ClickToProgress(JudgeWaitingRoomPage.EnterPrivateConsultationButton, PrivateConsultationRoomPage.LeavePrivateConsultationButton);
Has this been tested in a pipeline?
There should have been a reason for setting the timeout override.

2022-02-11 17:02 UTC, MichaelKeaneathmcts commented
VIH-7638 is the main task for all repairs, did you create a sub-task for this fault?

2022-02-11 17:08 UTC, ibthmcts commented
> [VIH-7638](https://tools.hmcts.net/jira/browse/VIH-7638) is the main task for all repairs, did you create a sub-task for this fault?

No. Rather all script repairs are committed to a single branch so a history of the fixes are all in one place.

2023-02-06 11:57 UTC, closed without merging