VIH-9835 mapped wrong object type
hmcts/vh-video-web pull request #2013
Opened 2023-05-12 14:42 UTC by will-craig

2023-05-12 14:45 UTC, shaed-parkar requested changes
The docs state this is an object with a single field UUID. A class wit a single field `uuid` would align with docs and also better protect the app from future changes in case pexip change the returned object in anyway.
https://docs.pexip.com/api_client/api_pexrtc.htm#onParticipantDelete

2023-05-12 14:47 UTC, shaed-parkar commented on VideoWeb/VideoWeb/ClientApp/src/typings.d.ts
> +    onParticipantDelete: (uuid: string) => void;
To be consistent here, may I suggest `PexipParticipantDeleted`
```suggestion
    onParticipantDelete: (participantUpdate: PexipParticipantDeleted) => void;
```

2023-05-12 14:48 UTC, shaed-parkar commented on VideoWeb/VideoWeb/ClientApp/src/app/waiting-space/services/video-call.service.ts
> +    private onParticipantDeletedSubject = new Subject<string>();
To keep in line with what the updated and created does, use a DTO

```suggestion
    private onParticipantDeletedSubject = new Subject<ParticipantDeleted>();
```

2023-05-19 12:03 UTC, shaed-parkar approved these changes

2023-05-19 13:20 UTC, komaldabhi1509 approved these changes

2023-05-22 12:14 UTC, merged